# Tratamento Inicial de Dados do ENEM 2022

## Objetivo

O dataset do ENEM é bem grande, e possui muitos parâmetros desnecessários para esse estudo, além de valores vazios. 

## Importanto Dados

In [45]:
import pandas as pd
import numpy as np

In [46]:
df = pd.read_csv("microdados_enem_2022/DADOS/MICRODADOS_ENEM_2022.csv", encoding="iso-8859-1", delimiter=";")

In [47]:
df

NU_INSCRICAO  NU_ANO  TP_FAIXA_ETARIA TP_SEXO  TP_ESTADO_CIVIL   
0        210057943671    2022               14       M                2  \
1        210057516120    2022               14       M                2   
2        210057280536    2022                5       F                1   
3        210055724397    2022                6       M                1   
4        210055097896    2022                4       M                0   
...               ...     ...              ...     ...              ...   
3476100  210056389903    2022                3       M                1   
3476101  210057205644    2022               14       F                2   
3476102  210056699189    2022                2       M                1   
3476103  210056983033    2022                3       M                1   
3476104  210056307777    2022                2       F                2   

         TP_COR_RACA  TP_NACIONALIDADE  TP_ST_CONCLUSAO  TP_ANO_CONCLUIU   
0                  2                 1                1                2  \
1                  1                 1                1               16   
2                  2                 1                1                2   
3                  3                 1                1                2   
4                  3                 1                1                1   
...              ...               ...              ...              ...   
3476100            1                 1                2                0   
3476101            1                 1                2                0   
3476102            1                 1                2                0   
3476103            3                 1                2                0   
3476104            3                 1                2                0   

         TP_ESCOLA  ...  Q016  Q017  Q018 Q019  Q020 Q021  Q022  Q023  Q024   
0                1  ...     B     A     A    A     A    A     A     A     A  \
1                1  ...     E     E     B    E     B    B     E     B     E   
2                1  ...     A     A     A    A     A    A     C     A     A   
3                1  ...     B     A     A    C     A    A     C     B     B   
4                1  ...     A     A     A    A     A    A     B     A     A   
...            ...  ...   ...   ...   ...  ...   ...  ...   ...   ...   ...   
3476100          2  ...     B     A     B    B     B    A     E     A     A   
3476101          2  ...     A     A     A    B     A    A     C     A     B   
3476102          2  ...     B     A     B    C     B    A     E     A     B   
3476103          3  ...     B     A     B    D     A    A     E     A     B   
3476104          2  ...     A     A     A    B     A    A     C     A     C   

         Q025  
0           A  
1           B  
2           B  
3           B  
4           A  
...       ...  
3476100     B  
3476101     B  
3476102     B  
3476103     B  
3476104     B  

[3476105 rows x 76 columns]

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3476105 entries, 0 to 3476104
Data columns (total 76 columns):
 #   Column                  Dtype  
---  ------                  -----  
 0   NU_INSCRICAO            int64  
 1   NU_ANO                  int64  
 2   TP_FAIXA_ETARIA         int64  
 3   TP_SEXO                 object 
 4   TP_ESTADO_CIVIL         int64  
 5   TP_COR_RACA             int64  
 6   TP_NACIONALIDADE        int64  
 7   TP_ST_CONCLUSAO         int64  
 8   TP_ANO_CONCLUIU         int64  
 9   TP_ESCOLA               int64  
 10  TP_ENSINO               float64
 11  IN_TREINEIRO            int64  
 12  CO_MUNICIPIO_ESC        float64
 13  NO_MUNICIPIO_ESC        object 
 14  CO_UF_ESC               float64
 15  SG_UF_ESC               object 
 16  TP_DEPENDENCIA_ADM_ESC  float64
 17  TP_LOCALIZACAO_ESC      float64
 18  TP_SIT_FUNC_ESC         float64
 19  CO_MUNICIPIO_PROVA      int64  
 20  NO_MUNICIPIO_PROVA      object 
 21  CO_UF_PROVA             int64  

Como podemos ver, a tabela tem 76 colunas. Muitas delas não são relevantes para a nossa análise (ex: vetor com as questões que o inscrito marcou). Outras possues um valor marcado com algo quando seria mais interessante se fosse NA (ex: valor 1 no tipo de escola quer dizer que não respondeu).<br><br>
A partir de agora, iremos eliminar aquelas colunas julgadas como não relevantes, e transformar os dados caso seja necessário.<br><br>
Tratamentos mais avançados ou bem específicos da análise que for feita serão feitos num código a parte.

## Eliminando Colunas Desnecessárias

As colunas podem ser vistas no diretório DICIONÁRIO.

In [49]:
# Todos os dados são do ENEM 2022
df.drop("NU_ANO", axis=1, inplace=True)

In [50]:
# O Estado Civil não é considerado relevante para as análises que serão feitas. 
# Ele não dá informações relevantes sobre o desempenho do candidato da prova, e nem possui relação com cotas
# Ano de conclusão de ensino médio também (o que é relevante é se está fazendo ou não)
df.drop("TP_ESTADO_CIVIL", axis=1, inplace=True)
df.drop("TP_ANO_CONCLUIU", axis=1, inplace=True)

In [51]:
# Quanto à região da escola, algumas informações podem ser relevantes
# Para esse trabalho, será considerado que apenas a UF da escola é relevante. O município é uma informação muito específica, e vai gerar um número muito alto de classes.
# Informações como localização da escola e estado de funcionamento podem ser bem legais, entretanto, para limitar o número de parâmetros, será considerado que saber se a escola
# é pública ou privada e em qual UF ela fica são informações suficientes
df.drop("CO_MUNICIPIO_ESC", axis=1, inplace=True)
df.drop("NO_MUNICIPIO_ESC", axis=1, inplace=True)
df.drop("TP_DEPENDENCIA_ADM_ESC", axis=1, inplace=True)
df.drop("CO_UF_ESC", axis=1, inplace=True)
df.drop("TP_LOCALIZACAO_ESC", axis=1, inplace=True)
df.drop("TP_SIT_FUNC_ESC", axis=1, inplace=True)

In [52]:
# Todos os dados sobre o local da prova serão considerados irrelevantes
df.drop("CO_MUNICIPIO_PROVA", axis=1, inplace=True)
df.drop("NO_MUNICIPIO_PROVA", axis=1, inplace=True)
df.drop("CO_UF_PROVA", axis=1, inplace=True)
df.drop("SG_UF_PROVA", axis=1, inplace=True)

In [53]:
# Sobre dados da prova objetivo, a informação sobre a presença do participante é desnecessária (podemos saber isso olhando se a nota está como NA ou não)
# Dados sobre qual o código da prova também não são considerados relevantes
# O vetor de respostas será eliminado, pois não iremos analisar quais questões cada aluno errou (motivo análogo para eliminr o vetor de gabarito)
# A língua estrangeira será eliminada também, pois ela é considerada irrelevante para as análises que serão feitas
df.drop("TP_PRESENCA_CN", axis=1, inplace=True)
df.drop("TP_PRESENCA_CH", axis=1, inplace=True)
df.drop("TP_PRESENCA_LC", axis=1, inplace=True)
df.drop("TP_PRESENCA_MT", axis=1, inplace=True)

df.drop("CO_PROVA_CN", axis=1, inplace=True)
df.drop("CO_PROVA_CH", axis=1, inplace=True)
df.drop("CO_PROVA_LC", axis=1, inplace=True)
df.drop("CO_PROVA_MT", axis=1, inplace=True)

df.drop("TX_RESPOSTAS_CN", axis=1, inplace=True)
df.drop("TX_RESPOSTAS_CH", axis=1, inplace=True)
df.drop("TX_RESPOSTAS_LC", axis=1, inplace=True)
df.drop("TX_RESPOSTAS_MT", axis=1, inplace=True)

df.drop("TP_LINGUA", axis=1, inplace=True)

df.drop("TX_GABARITO_CN", axis=1, inplace=True)
df.drop("TX_GABARITO_CH", axis=1, inplace=True)
df.drop("TX_GABARITO_LC", axis=1, inplace=True)
df.drop("TX_GABARITO_MT", axis=1, inplace=True)

In [54]:
# Sobre os dados da Redação, o único que interessa é a nota total da redação
df.drop("TP_STATUS_REDACAO", axis=1, inplace=True)

df.drop("NU_NOTA_COMP1", axis=1, inplace=True)
df.drop("NU_NOTA_COMP2", axis=1, inplace=True)
df.drop("NU_NOTA_COMP3", axis=1, inplace=True)
df.drop("NU_NOTA_COMP4", axis=1, inplace=True)
df.drop("NU_NOTA_COMP5", axis=1, inplace=True)

In [55]:
# Sobre o Formulário Socioeconômico, há várias informações específicas que podem ser interessantes em análises específicas
# Para esse trabalho, a única considerada relevante é sobre a renda familiar (Questão 6). As outras serão eliminadas
eliminar = [f"Q{i:03d}" for i in range(1, 26)]  # as colunas vão de Q001 até Q025
eliminar.remove("Q006")  # questão da renda familiar
for col in eliminar:
    df.drop(col, axis=1, inplace=True)

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3476105 entries, 0 to 3476104
Data columns (total 16 columns):
 #   Column            Dtype  
---  ------            -----  
 0   NU_INSCRICAO      int64  
 1   TP_FAIXA_ETARIA   int64  
 2   TP_SEXO           object 
 3   TP_COR_RACA       int64  
 4   TP_NACIONALIDADE  int64  
 5   TP_ST_CONCLUSAO   int64  
 6   TP_ESCOLA         int64  
 7   TP_ENSINO         float64
 8   IN_TREINEIRO      int64  
 9   SG_UF_ESC         object 
 10  NU_NOTA_CN        float64
 11  NU_NOTA_CH        float64
 12  NU_NOTA_LC        float64
 13  NU_NOTA_MT        float64
 14  NU_NOTA_REDACAO   float64
 15  Q006              object 
dtypes: float64(6), int64(7), object(3)
memory usage: 424.3+ MB


Após as eliminações, temos um total de 16 colunas.
<br><br>
Entretanto, muitas dessas possues variáveis categóricas, e portanto, precisam receber um tratamento a mais.

## Tratamento dos Dados

A prioridade é fazer o tratamento das variáveis categóricas. Além disso, algumas colunas possuem valores que deveriam ser NA, mas estão com algum outro valor (ex: na coluna de COR/RAÇA, 0 indica que não declarou resposta).

### Remoção de NA

In [57]:
# Células que envolvem algum valor "não informado" serão alteradas para NA
df["TP_COR_RACA"].replace({0: np.nan, 6: np.nan}, inplace=True)
df["TP_NACIONALIDADE"].replace(0, np.nan, inplace=True)
df["TP_ESCOLA"].replace(1, np.nan, inplace=True)

In [58]:
# Como agora só há duas opções de escola (Pública ou Privada), dá para usar só dois valores
# Pública = 1 e Privada = 0 (pode ser interpretado como "elegível à cota?")
df["TP_ESCOLA"].replace({2: 1, 3: 0}, inplace=True)
df["TP_ESCOLA"].value_counts()

TP_ESCOLA
1.0    1105355
0.0     212205
Name: count, dtype: int64

In [59]:
# Quantos valores ainda vamos ter se dropar valores na?
original = len(df)
removido = df.dropna().shape[0]
print(f"Original: {original}")
print(f"Após remoção: {removido}")
print(f"Porcentagem do original: {round(100*removido/original, 2)}")

Original: 3476105
Após remoção: 669781
Porcentagem do original: 19.27


In [60]:
# Deletando valores na
df.dropna(inplace=True)

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 669781 entries, 40 to 3476102
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   NU_INSCRICAO      669781 non-null  int64  
 1   TP_FAIXA_ETARIA   669781 non-null  int64  
 2   TP_SEXO           669781 non-null  object 
 3   TP_COR_RACA       669781 non-null  float64
 4   TP_NACIONALIDADE  669781 non-null  float64
 5   TP_ST_CONCLUSAO   669781 non-null  int64  
 6   TP_ESCOLA         669781 non-null  float64
 7   TP_ENSINO         669781 non-null  float64
 8   IN_TREINEIRO      669781 non-null  int64  
 9   SG_UF_ESC         669781 non-null  object 
 10  NU_NOTA_CN        669781 non-null  float64
 11  NU_NOTA_CH        669781 non-null  float64
 12  NU_NOTA_LC        669781 non-null  float64
 13  NU_NOTA_MT        669781 non-null  float64
 14  NU_NOTA_REDACAO   669781 non-null  float64
 15  Q006              669781 non-null  object 
dtypes: float64(9), int64(4)

### Tratando Variáveis Categóricas

In [62]:
# Faixa etária já está no formato de Ordinal Encoding, então será mantida (por ter uma certa noção de ordem)
values = list(df["TP_FAIXA_ETARIA"].unique())
values.sort()
values

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [63]:
# Sexo será alterado usando apenas uma coluna
# F -> 0, M -> 1
df["TP_SEXO"].replace({"F": 0, "M": 1}, inplace=True)
df["TP_SEXO"].unique()

array([0, 1])

In [64]:
df["TP_COR_RACA"].value_counts()

TP_COR_RACA
1.0    328473
3.0    265281
2.0     61609
4.0     11466
5.0      2952
Name: count, dtype: int64

In [65]:
# Cor/Raça precisa de One Hot encoding
one_hot = pd.get_dummies(df["TP_COR_RACA"], prefix="COR_RACA")
df = df.join(one_hot)
df.drop("TP_COR_RACA", axis=1, inplace=True)
df.columns

Index(['NU_INSCRICAO', 'TP_FAIXA_ETARIA', 'TP_SEXO', 'TP_NACIONALIDADE',
       'TP_ST_CONCLUSAO', 'TP_ESCOLA', 'TP_ENSINO', 'IN_TREINEIRO',
       'SG_UF_ESC', 'NU_NOTA_CN', 'NU_NOTA_CH', 'NU_NOTA_LC', 'NU_NOTA_MT',
       'NU_NOTA_REDACAO', 'Q006', 'COR_RACA_1.0', 'COR_RACA_2.0',
       'COR_RACA_3.0', 'COR_RACA_4.0', 'COR_RACA_5.0'],
      dtype='object')

In [66]:
df["TP_NACIONALIDADE"].value_counts()

TP_NACIONALIDADE
1.0    655438
2.0     11523
4.0      1676
3.0      1144
Name: count, dtype: int64

In [67]:
# Nacionalidade usa One Hot também
one_hot = pd.get_dummies(df["TP_NACIONALIDADE"], prefix="NACIONALIDADE")
df = df.join(one_hot)
df.drop("TP_NACIONALIDADE", axis=1, inplace=True)
df.columns

Index(['NU_INSCRICAO', 'TP_FAIXA_ETARIA', 'TP_SEXO', 'TP_ST_CONCLUSAO',
       'TP_ESCOLA', 'TP_ENSINO', 'IN_TREINEIRO', 'SG_UF_ESC', 'NU_NOTA_CN',
       'NU_NOTA_CH', 'NU_NOTA_LC', 'NU_NOTA_MT', 'NU_NOTA_REDACAO', 'Q006',
       'COR_RACA_1.0', 'COR_RACA_2.0', 'COR_RACA_3.0', 'COR_RACA_4.0',
       'COR_RACA_5.0', 'NACIONALIDADE_1.0', 'NACIONALIDADE_2.0',
       'NACIONALIDADE_3.0', 'NACIONALIDADE_4.0'],
      dtype='object')

In [68]:
# Ano de Conclusão do EM 
values = list(df["TP_ST_CONCLUSAO"].unique())
values.sort()
values

[2]

In [69]:
# Note que todos os participantes restantes estão no último ano do Ensino Médio. Portanto, essa coluna pode ser eliminada
df.drop("TP_ST_CONCLUSAO", axis=1, inplace=True)

In [70]:
# Tipo de Escola já foi corrigido
df["TP_ESCOLA"].unique()

array([1., 0.])

In [71]:
# Tipo de Ensinado será corrigido usando uma coluna
# 0 -> Ensino Regular, 1 -> Ensino Especial
df["TP_ENSINO"].replace({1: 0, 2: 1}, inplace=True)
df["TP_ENSINO"].unique()

array([0., 1.])

In [72]:
df["IN_TREINEIRO"].unique()

array([0])

In [73]:
# Como não há treineiros, essa coluna pode ser eliminada
df.drop("IN_TREINEIRO", axis=1, inplace=True)

In [74]:
# Número de UFs
len(df["SG_UF_ESC"].unique())

27

In [76]:
# UFs serão separadas por região
regioes = {
    "NORTE": ["AC", "RO", "AM", "RR", "PA", "AP", "TO"],
    "NORDESTE": ["MA", "PI", "BA", "CE", "RN", "PB", "PE", "AL", "SE"],
    "CENTROOESTE": ["MT", "GO", "MS", "DF"],
    "SUDESTE": ["MG", "ES", "RJ", "SP"],
    "SUL": ["PR", "SC", "RS"]
}
for regiao, UFs in regioes.items():
    df["SG_UF_ESC"].replace(UFs, regiao, inplace=True)
df["SG_UF_ESC"].unique()

array(['NORDESTE', 'SUDESTE', 'CENTROOESTE', 'NORTE', 'DF', 'SUL'],
      dtype=object)

In [84]:
df["SG_UF_ESC"].value_counts()

SG_UF_ESC
SUDESTE        251265
NORDESTE       211248
SUL             88808
NORTE           56047
CENTROOESTE     47315
DF              15098
Name: count, dtype: int64

In [85]:
# One Hot Encoding da região
one_hot = pd.get_dummies(df["SG_UF_ESC"], prefix="REGIAO")
df = df.join(one_hot)
df.drop("SG_UF_ESC", axis=1, inplace=True)
df.columns

Index(['NU_INSCRICAO', 'TP_FAIXA_ETARIA', 'TP_SEXO', 'TP_ESCOLA', 'TP_ENSINO',
       'NU_NOTA_CN', 'NU_NOTA_CH', 'NU_NOTA_LC', 'NU_NOTA_MT',
       'NU_NOTA_REDACAO', 'Q006', 'COR_RACA_1.0', 'COR_RACA_2.0',
       'COR_RACA_3.0', 'COR_RACA_4.0', 'COR_RACA_5.0', 'NACIONALIDADE_1.0',
       'NACIONALIDADE_2.0', 'NACIONALIDADE_3.0', 'NACIONALIDADE_4.0',
       'REGIAO_CENTROOESTE', 'REGIAO_DF', 'REGIAO_NORDESTE', 'REGIAO_NORTE',
       'REGIAO_SUDESTE', 'REGIAO_SUL'],
      dtype='object')

In [86]:
# Faixa Salarial
df["Q006"].value_counts()

Q006
1     157681
2      95658
3      77074
4      59293
7      48684
6      47253
5      36449
0      25361
8      20601
16     15439
9      15317
11     14468
12     13694
14     11417
15     10823
10     10540
13     10029
Name: count, dtype: int64

In [82]:
# Q006 indica faixa salarial. Por ter noção de ordem, será usado Ordinal Encoding
conversao = {char: (ord(char) - ord("A") + 1) for char in "ABCDEFGHIJKLMNOPQ"}
df["Q006"].replace(conversao, inplace=True)
values = df["Q006"].unique()
values.sort()
values

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [87]:
# Como df ficou após modificações
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 669781 entries, 40 to 3476102
Data columns (total 26 columns):
 #   Column              Non-Null Count   Dtype  
---  ------              --------------   -----  
 0   NU_INSCRICAO        669781 non-null  int64  
 1   TP_FAIXA_ETARIA     669781 non-null  int64  
 2   TP_SEXO             669781 non-null  int64  
 3   TP_ESCOLA           669781 non-null  float64
 4   TP_ENSINO           669781 non-null  float64
 5   NU_NOTA_CN          669781 non-null  float64
 6   NU_NOTA_CH          669781 non-null  float64
 7   NU_NOTA_LC          669781 non-null  float64
 8   NU_NOTA_MT          669781 non-null  float64
 9   NU_NOTA_REDACAO     669781 non-null  float64
 10  Q006                669781 non-null  int64  
 11  COR_RACA_1.0        669781 non-null  bool   
 12  COR_RACA_2.0        669781 non-null  bool   
 13  COR_RACA_3.0        669781 non-null  bool   
 14  COR_RACA_4.0        669781 non-null  bool   
 15  COR_RACA_5.0        669781 non-null  

## Conclusão

Infelizmente, muitas pessoas não respondem alguns campos (principalmente o de informar se a escola é pública ou privada). Por causa disso, um dataset de mais de 3 milhões de observações foi reduzido para 600 mil observações. Entretanto, ainda é um número considerável para fazer análises.

In [15]:
# Slavando dataset
df.to_csv("enem2022_dataset.csv", index=False)